version: '3.8'

services:
  # Database
  mysql:
    image: mysql:8.0
    container_name: banking_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: banking_system
      MYSQL_USER: banking_user
      MYSQL_PASSWORD: banking_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - banking_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: banking_backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/banking_system
      SPRING_DATASOURCE_USERNAME: banking_user
      SPRING_DATASOURCE_PASSWORD: banking_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - banking_network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: banking_frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - banking_network

volumes:
  mysql_data:

networks:
  banking_network:
    driver: bridge